"""empty message

Revision ID: 08d85b48a311
Revises: 94d67edb0d0e
Create Date: 2020-10-30 10:38:01.055671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d85b48a311'
down_revision = '94d67edb0d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tem', sa.String(length=90), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tem')
    # ### end Alembic commands ###
