"""empty message

Revision ID: 2cc7962578e3
Revises: 08d85b48a311
Create Date: 2020-10-30 10:39:20.995598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cc7962578e3'
down_revision = '08d85b48a311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tem', mysql.VARCHAR(length=90), nullable=True))
    # ### end Alembic commands ###
